# -*- coding: utf-8 -*-
"""Copy of PythonCode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/149DeLB9nrK7_mj29lXL2Y_uHC910Nn57
"""

print("Olá usuário")

print("Estou aprendendo Python")

"""ESTUDO DE PYTHON"""

1 + 1

10 - 2

# Esse é um comentário em Python

# Multiplicação
2 * 2

# Divisão
10/4

a = 4
b = 6

a + b

# Criando um variável do tipo string
frase = "Python para análise de dados"

frase[0]

frase[0:10]

frase[10:]

frase[:17]

frase.count("dados")

frase.lower()

frase.upper()

frase.replace("Python", "Frases")

frase = frase.upper()

frase